---
output:
  html_document: default
  pdf_document: default
---
**Author:** [Mackenzie O'Brien]

* * *

#### Leemis - Chapter 2: 

```{r}
# codes for Chapter 2-page 4 are already entered below as examples
2+9*4 # Place spaces around operator
4+3/10^2 #Exponentiation first, then division, then addition
4+(3/10)^2 #division first, then exponentiation, then addition
(4+3)/10^2 #addition first, then addition, then exponentiation
2*3 - #prompt for more input
+7 #completed command 
1/4 # the display supprsses trailing zeros
1/3 #default seven display digits
8*10^3 # exponentiation first
1111111* 1111111 # no commas on constants; scientific notation
pi #built in constant
options(digits = 10) # display 10 digits
pi #pi to 10 digits
 #options(digits=50) # display 50 digits--invalid
 options(digits=22) # display 22 digits
 pi # pi to 22 digits
 1111111*1111111 # now exact
 789^ 10 #scientific notation
 17.046875 #stored exactly
 6.02214e23 # not exact
 1/17^7 # a small number
 1/0 #Infinity
 Inf-Inf #infinity - infinity
 -1/0 #negative infinity
 0/0 #not a number
 (-9)^(1/2) #square root of negative nine
 37%/%5 #integer part of a fraction
 37%%5 #remainder function
```

#### Leemis- Chapter 3:

```{r}
# enter your code for Chapter 3 here
x=2 #assign two the the object x
x #display x
y=4 #assign four to y
y #display y
z<- 3.7 #assign 3.7 to z
z #display z
x <- x +1 #increment x
x
x = y = z = 5 #set x, y, and z to 5
x=3; y=4; #semi-colon separates the two commands
x+y #sum
x*y #product
x^y #3^4
y%%x # y modulo x
ls() #display object names
rm(x) #remove (unassign) x
# x #the object x no longer exists
ls() #display object names
rm(y,z) #remove y and z
objects() #display object names
rm(list=ls()) #remove all objects in current session
CashOnHand = 155 # meaningful object name using uppercase
cash_on_hand = 155 #meaningful object name using underscore
cash.on.hand= 155 #meaningful object name using periods
objects() # display object names
```

#### Leemis- Chapter 4:

```{r}
# enter your code for Chapter 4 here
1:10 # a vector of the first ten integers
-3:5 #integers -3 to 5
5:-3 #integers from 5 to -3
1:100 #integers from 1 to 100
x=1:100 #stores the integers 1 to 100 in x
4.5:25 #won't make it to 25
c(2, -3, 4, 0) # a four-element vector
x=c(2,-3,4,0) #x is a four element vector
x #display x
y = c (1,NA,-3) #y is a three element vector
y #display y
z=c(x,y,-1:3) #z is the concatentation of x,y, and -1:3
z #display z
seq(2,20, by=2) # a vector from 2 to 20 by 2
seq(2,20,length.out =10) # a vector from 2 to 20 of length 10
seq(20,1,by=-3) # a vector from 20 to 2 by -3
rep(5,4) #repeat 5 four times
rep (1:3,2) #repeat 1:3 two times
rep(seq(1,5,by=2),2) #repeat (1,3,5) two times
rep(c(1,5),c(2,4)) #repeat 1 twice and 5 four times
rep(seq(1,5,2),seq(1,5,2)) # one 1, then 3 threes, and five 5s
rep(1:3,each =4) # four 1s, then 4 2s, then 4 3s
x=c(2,0,-1,6, #continue input
    + 7,8) #x is a 6 element vector
x #display x
x[3] #third element of x
x[3:6] #elements 3 through 6
x[c(6,3,6,1)] #elements of 6,3,6,1
x[-4] # all elements except the 4th
x[-4:-6] #all elements except the 4th-6th
x[-c(2,5)] # all elements except the 2nd and 5th
#x[c(-2,5)] # don't mix positive and negative subscripts, error
x[3.3] # R truncates toward zero
x[0.8] #use integer subscripts
x[-1.8] # use integer subscripts
x=NULL # set x to a vector with no elements
x #display x
x[seq(1,9,2)]=11:15 #fill elements with odd subscripst only
x #display x
(1:10) +3 # add 3 to each element of the vector
1:10 +3 #precedence of : vs +
1;10 *7 # multiply each element by 7
1:10/20 #divide each element by 20
(1:10)^3 # the first ten perfect cubes
2^(1:10) #the first ten powers of 2
2^ c(2,-3,4,0) #various powers of 2
x=c(-1,0,1) # define x
x/x # ratio of x to x
y=4*x #define y to be (-4,0,4)
x*y # product taken element-wise
y^x # element-wise exponentiation
z=c(y,y) # z has length 6
z # display z
z^x # recycle the balues once you run out
y^c(1,2,3,9) # lengths of the vecotrs are not multiples

```


